### PR TITLE
Fix incompatibility of Util\Assertion with beberlei/assert v3.2.3

### PR DESCRIPTION
**Pull request by codeliner**
Fixes:

image

### CODE REVIEW

**Comment by codeliner** [comment]
Tried to fix the issue but we would need to pin beberlei/assert to 3.2.3. I'm not happy with such a solution. Opened an issue upstream and awaiting feedback: https://github.com/beberlei/assert/issues/287

**Comment by prolic** [comment]
@codeliner let's wait for feedback on the assert lib issue and then go from there. We can postpone the next release a little.

**Comment by codeliner** [comment]
upstream issue is fixed. I've added problematic versions of berberlei/assert to composer conflict section

**Comment by prolic** [comment]
Great, can you take care of release? Thanks

**Pull request merged**
