### PR TITLE
Set recordedEvent back to ArrayIterator when rolling back transaction

### PR DESCRIPTION
**Pull request by prolic**
... also updates coveralls to ^1.0

### CODE REVIEW

**Comment by prolic** [comment]
@codeliner this! :)

**Comment by prolic** [comment]
I hope it's okay to do all in one PR, if neccessary I can split into multiples, too.

**Comment by codeliner** [comment]
that's a good question. Would be good to have the bugfix in a separate PR so that we can link to it in the changelog/release note. I'm off again for 2 hours and merge it later.

**Comment by prolic** [comment]
see: https://github.com/prooph/event-store/pull/160 & https://github.com/prooph/event-store/pull/161

**Pull request closed without merging**
