### PR TITLE
PHP 8.2 compatibility (and some more)

### PR DESCRIPTION
**Pull request by zluiten**
Most of these changes are done with the help of [rector](https://github.com/rectorphp/rector).

  * Ensure compatibility with PHP 8.2 (dynamic properties)
  * Add explicit public visibility to remaining constants
  * Use array spread operator instead of array_merge where possible
  * Add null default to nullable properties properties that have no default
  * Add typed properties and return types where possible
  * Simplify empty() function calls on empty arrays
  * Update licenses to 2023

### CODE REVIEW

**Comment by fritz-gerneth** [comment]
Not having checked every single file, but looks good to me

**Review by prolic — APPROVED** [review]

**Comment by prolic** [comment]
Thanks @zluiten! Great work!

**Comment by prolic** [comment]
Currently some builds are failing, @zluiten if you have time to look into those, would be great. Otherwise I try to check when I have time. I'd like to have all green builds before a release.

**Comment by zluiten** [comment]
Thanks @prolic for the quick review/merge! The fix is here #431.

**Comment by szepczynski** [comment]
is any chance to support php 8?

**Pull request merged**
