### PR TITLE
require php 7.4

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
see https://github.com/prooph/event-store-client/issues/107

**Comment by prolic** [comment]
I was using rector for the most part. Did its job quite good, but had to change some things manually. So please review carefully.

**Comment by prolic** [comment]
ping @enumag @sandrokeil @codeliner

**Comment by enumag** [comment]
Also I'm all for the `callable` => `Closure` change. :+1:

**Pull request merged**
