### PR TITLE
add ReadOnlyEventStore interface

### PR DESCRIPTION
**Pull request by prolic**
resolves: https://github.com/prooph/event-store/issues/250

### CODE REVIEW

**Comment by codeliner** [comment]
easy pick ;)

**Comment by codeliner** [comment]
@prolic when you write:

Closes #250

**Comment by prolic** [comment]
Ah good to know, thx

**Comment by codeliner** [comment]
the cool thing is, that github adds a note to the linked issue that it was closed by ...

**Comment by codeliner** [comment]
hehe resolves also work: https://help.github.com/articles/closing-issues-via-commit-messages/
but without double point ;)

**Pull request merged**
