### PR TITLE
Multiple repo get calls sametransaction same instance

### PR DESCRIPTION
**Pull request by basz**
I feel you do not understand me - or me you - hope this helps

fix for #179

### CODE REVIEW

**Comment by codeliner** [comment]
@prolic your thoughts?

**Comment by prolic** [comment]
well, okay for me, when it's okay for @codeliner 

@basz Can you change the base branch to develop?

**Comment by codeliner** [comment]
if it is ok for @prolic it is ok for me, too ;)

**Comment by prolic** [comment]
Will release a new minor version this weekend.

**Pull request merged**
