### PR TITLE
Fix PersistentSubscriptionSettingsBuilder

### PR DESCRIPTION
**Pull request by enumag**
Closes https://github.com/prooph/event-store-client/issues/101

### CODE REVIEW

**Comment by prolic** [comment]
code style check failed, see https://travis-ci.org/prooph/event-store/jobs/589002992

**Comment by enumag** [comment]
Fixed.

**Comment by prolic** [comment]
thank you!

**Comment by SlayerBirden** [comment]
@enumag @prolic  thank you!! sorry I wanted to submit a PR but have a business trip this week.

**Pull request merged**
